[package]
name = "bullpen-dex-messaging"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
iggy = "0.6.210"
async-nats = "0.41.0"
async-trait = "0.1.88"
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "rt"] }
serde = { workspace = true, features = ["derive"] }
serde_json = {workspace = true}
dotenv = "0.15.0"
snafu = { workspace = true, features = ["backtrace"] }
futures = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
prost = "0.13.5"
rand = {workspace = true}
strum = "0.27.1"
redis = {workspace = true}
chrono = {workspace = true, features = ["serde"]}

[build-dependencies]
prost-build = "0.13.5"

[[bin]]
name = "consumer"
path = "src/bin/consumer.rs"

[[bin]]
name = "nats_simulator"
path = "src/bin/nats_simulator.rs"